### ISSUE TITLE
Global Before/After request hooks are not working

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpbook#38]
Imagine following code:

```
{{+request
   request.headers = { "enforced-header": "foo"};   
}}
{{+response
    console.info(response.body);
}}

# @name request1
GET /v1/foo

# @name request2
GET /v1/foo2
```

Running this in std. vs-plugin or cli works fine for both requests, but in httpbook it doesn't. Looks like the global hooks are not evaluated

**Comment by rngtng** [comment]
Btw. I fixed this with the workaround of moving the before request hook into a plugin. still I'd expect behaviour of httpbook, same as text version...

**Comment by AnWeber** [comment]
the reason is that I parse [the whole file from disk](https://github.com/AnWeber/httpbook/blob/c8c8463b00fd6c820e84b10a9a2056f7d5a267dc/src/extension/notebook/httpNotebookKernel.ts#L116-L120) and [the executing cell from the content of the cell](https://github.com/AnWeber/httpbook/blob/c8c8463b00fd6c820e84b10a9a2056f7d5a267dc/src/extension/notebook/httpNotebookKernel.ts#L123) and just patch those together.
However, this causes my global script logic to not work correctly. When parsing, [the global script is attached directly to the HttpRegion and not thie httpFile](https://github.com/AnWeber/httpyac/blob/main/src/parser/javascriptHttpRegionParser.ts#L109-L138). The events `request`, `response`, `streaming` and `responseLogging` can be easily changed. The Event `after` gives me problems.

**Comment by AnWeber** [comment]
The bug was fixed with the new version of vscode-httpyac. Updating httpbook is not necessary

**Comment by rngtng** [comment]
nice!

**Comment by AnWeber** [comment]
I don't really like the two newly created hooks (BeforeHttpRegion and AfterHttpRegion) in the plugin API. Please don't consider these two hooks as part of the api, That is why I have not yet included them in the documentation. I will probably remove them again by extending my hook system. And cool that it works now.

**Comment by AnWeber** [comment]
I have removed the two hooks `BeforeHttpRegion` and `AfterHttpRegion` and replaced them with an `ExecuteHook` + merge Functionality of hooks. In detail, a different order now occurs between interceptor/ hook calls between HttpFile and HttpRegion hooks. However, these should not be a major problem. 

Before: httpRegion - hooks => httpRegion - afterLoop => httpFile hooks => httpFile - afterLoop
Now: httpRegion - hooks => httpFile hooks => httpRegion - afterLoop => httpFile - afterLoop
