### ISSUE TITLE
websocket response inaccurate rendered as a cell

### ISSUE THREAD

**Issue by zuisong** [AnWeber/httpbook#51]
steps:
1. create a notebook has follow content

```
WS wss://demo.piesocket.com/v3/channel_1?api_key=oCdCMcMPQpbvNjUIzqtvF1d2X2okWpDQj4AwARJuAgtjhzKxVEjQU6IdCjwm&notify_self
```

2. send request

them, response has been render as a cell

![image](https://user-images.githubusercontent.com/19145952/165066791-b7c915d5-3b3e-4619-9a28-9118abdd97ee.png)

**Comment by AnWeber** [comment]
@zuisong Hello, thank you for reporting. I have overlooked that. The cause is that the response is written to the * .http file by default, but is not recognized as a response when parsing ([only http works, error only with websocket, grpc, sse, ...](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/parse/responseHttpRegionParser.ts#L23)). Workaround would currently be to disable the setting `httpbook.saveWithOutputs`, then the response is not saved.

**Comment by zuisong** [comment]
It works for me, thanks

![image](https://user-images.githubusercontent.com/19145952/165205096-979148e4-49ba-46a9-8f6c-6515c94ab57b.png)

**Comment by AnWeber** [comment]
But I will also add that it works without workaround :-)

**Comment by AnWeber** [comment]
Fix will be delivered with the next version of `vscode-httpyac`. `httpbook` does not need any update. thx
