### ISSUE TITLE
The cells are modified after execution

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#53]
For some time now, the results of the queries are inserted in the cell, like this:
POST ------- HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
**connection: close
date: Tue, 10 May 2022 11:51:54 GMT
content-type: application/json; charset=utf-8
server: Kestrel
content-length: 5832**

Is it when saving the file, closing it or closing VSCode, I don't know exactly when this change is made?

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
httpBook v 3.1.0

**Comment by AnWeber** [comment]
I was able to reproduce it just now. It seems that currently the parser does not distinguish correctly between request header and response header. I'll take a look at it.

**Comment by AnWeber** [comment]
The response header symbol was incorrectly marked as request header. This caused [httpbook to assume that the area belonged to the code and not only to the OutputCell](https://github.com/AnWeber/httpbook/blob/main/src/extension/notebook/httpNotebookSerializer.ts#L87). The bug will be fixed with the next update of vscode-httpyac.

**Comment by AnWeber** [comment]
@dlucazeau v5.4.2 of vscode-httpyac is published. thx
