### ISSUE TITLE
feature request: make response JSON payload foldable

### ISSUE THREAD

**Issue by james-yin** [AnWeber/httpbook#95]
This is a new feature or enhancement request.

Make the output response JSON payload foldable (collapsible) just like how we can currently fold the request JSON body.

**Comment by AnWeber** [comment]
The Output uses a VSCode internal Feature. Does this not provide a JSON View which is foldable? Could you pleased add a.screenshot?

**Comment by james-yin** [comment]
Here's a screenshot showing folding widget in the request but not in the response. Thanks for looking into this:

![image](https://github.com/AnWeber/httpbook/assets/7233400/96e43801-f47e-411a-8d5a-98ec73537aad)

**Comment by AnWeber** [comment]
I didn't know that at all. I actually only use vscode-httpyac myself (without notebook extension) and that's why I didn't fall over it. You can solve your problem by installing my [Monaco Editor extension](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook-monacorenderer). It will use the same editor as VSCode internally to display the JSON. However, I thought so far that this has no more use. Maybe I should update it again.

But you should also make a bug in the repo of VSCode, since the folding support should already be part of the base. It should be extension [markdown-language-features](https://github.com/microsoft/vscode/blob/2d502be79d044ed34fcea16eeb02cf98b789789c/extensions/markdown-language-features/package.json#L49) in VSCode Repo

**Comment by AnWeber** [comment]
@james-yin  Sorry, but I did not quite understand the error. The Monaco Editor is actually only a renderer and has no file access, but runs in a browser sandbox without file access.
Then I would suggest you go the way of a ticket directly in VSCode. I just use the built-in display here which it does not support.
